# Generated by Django 6.0.2 on 2026-08-28 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_cartao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeGrupo', models.CharField(max_length=50, unique=True, verbose_name='Grupo de Despesa')),
            ],
            options={
                'verbose_name': 'Grupo de Despesa',
                'verbose_name_plural': 'Grupos de Despesas',
                'db_table': 'grupo',
                'ordering': ['nomeGrupo'],
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEspecie', models.CharField(max_length=50, unique=True, verbose_name='Espécie')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='especies', to='app_despesa.grupo', verbose_name='Grupo de Despesa')),
            ],
            options={
                'verbose_name': 'Espécie de Despesa',
                'verbose_name_plural': 'Espécies de Despesas',
                'db_table': 'especie',
                'ordering': ['nomeEspecie'],
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('local', models.CharField(blank=True, max_length=100, verbose_name='Local')),
                ('data', models.DateField(verbose_name='Data')),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('DEBITO', 'Débito em Conta'), ('CARTAO', 'Cartão de Crédito')], default='DINHEIRO', max_length=50, verbose_name='Forma de Pagamento')),
                ('origem', models.CharField(choices=[('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional')], default='NACIONAL', max_length=15, verbose_name='Origem da Compra')),
                ('parcela', models.PositiveIntegerField(default=1, verbose_name='Número de Parcelas')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('cartao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cartao.cartaocreate', verbose_name='Cartao')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='despesas_especie', to='app_despesa.especie', verbose_name='Espécie')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='despesa_gupo', to='app_despesa.grupo', verbose_name='Grupo de Despesa')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'db_table': 'despesa',
                'ordering': ['-data'],
            },
        ),
    ]
