# Generated by Django 6.0.2 on 2026-09-05 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(max_length=100, verbose_name='Fonte Pagadora')),
                ('descricao', models.CharField(blank=True, max_length=100, verbose_name='Descrição')),
                ('data_recebimento', models.DateField(verbose_name='Data de Recebimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Valor (R$)')),
                ('categoria', models.CharField(choices=[('13ºSALARIO', '13º Salário'), ('EVENTUAL', 'Eventual'), ('FREELANCER', 'Freelancer'), ('INVESTIMENTO', 'Investimento'), ('OUTROS', 'Outras Receitas'), ('RESTITUICAO', 'Restituição de IR'), ('SALARIO', 'Salário')], default='SALARIO', max_length=50, verbose_name='Categoria')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'db_table': 'receita',
                'ordering': ['-data_recebimento'],
            },
        ),
    ]
