# Generated by Django 6.0.2 on 2026-08-28 22:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaParcelaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveIntegerField(verbose_name='Número da Parcela')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Parcela')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Parcela do Cartão',
                'verbose_name_plural': 'Parcelas do Cartão',
                'db_table': 'despesa_parcela_cartao',
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='FaturaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano')),
                ('mes', models.PositiveIntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], verbose_name='Mês')),
                ('data_fechamento', models.DateField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('total_encargos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Encargos')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Pago')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'db_table': 'fatura',
            },
        ),
        migrations.CreateModel(
            name='CartaoCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(max_length=100, verbose_name='Nome impresso no cartão')),
                ('banco', models.CharField(max_length=50, verbose_name='Banco Emissor')),
                ('nome_cartao', models.CharField(max_length=100, verbose_name='Nome do cartão')),
                ('bandeira', models.CharField(choices=[('MASTERCARD', 'Mastercard'), ('VISA', 'Visa'), ('ELO', 'Elo')], max_length=50, verbose_name='Bandeira')),
                ('categoria', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoria (Ex: Nanquim, Black)')),
                ('final', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Digite exatamente 4 dígitos numéricos')], verbose_name='Final do cartão')),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Limite de Compra')),
                ('dia_vencimento', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Dia deve ser entre 1 e 31'), django.core.validators.MaxValueValidator(31, 'Dia deve ser entre 1 e 31')], verbose_name='Dia de Vencimento')),
                ('dia_limite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Dia deve ser entre 1 e 31'), django.core.validators.MaxValueValidator(31, 'Dia deve ser entre 1 e 31')], verbose_name='Dia de Fechamento (Melhor dia de compra)')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10, verbose_name='Status')),
                ('tipo_cartao', models.CharField(choices=[('TITULAR', 'Titular'), ('DEPENDENTE', 'Dependente'), ('ESTUDANTE', 'Estudante')], default='TITULAR', max_length=20, verbose_name='Tipo de cartão')),
                ('virtual', models.BooleanField(default=False, help_text='Marque sim se for cartão virtual', verbose_name='Cartão Virtual')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='Data da criação')),
                ('atualizado_em', models.DateField(auto_now=True, verbose_name='Última atualização')),
                ('cartao_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to='app_cartao.cartaocreate', verbose_name='Titular (se for dependente)')),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartões',
                'db_table': 'cartao',
                'ordering': ['nome_cartao'],
            },
        ),
    ]
