# Generated by Django 6.0.2 on 2026-08-28 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_cartao', '0001_initial'),
        ('app_despesa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesaparcelacartao',
            name='despesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_cartao', to='app_despesa.despesa', verbose_name='Despesa'),
        ),
        migrations.AddField(
            model_name='faturacartao',
            name='cartao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='app_cartao.cartaocreate'),
        ),
        migrations.AddConstraint(
            model_name='cartaocreate',
            constraint=models.UniqueConstraint(fields=('banco', 'bandeira', 'final'), name='unique_cartao_fisico'),
        ),
        migrations.AddConstraint(
            model_name='faturacartao',
            constraint=models.UniqueConstraint(fields=('cartao', 'ano', 'mes'), name='unique_fatura_por_cartao_ano_mes'),
        ),
        migrations.AlterUniqueTogether(
            name='faturacartao',
            unique_together={('cartao', 'ano', 'mes')},
        ),
    ]
