# Generated by Django 6.0.2 on 2026-09-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestimentoCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_investimento', models.CharField(max_length=100, unique=True, verbose_name='Nome do Investimento')),
                ('tipo', models.CharField(choices=[('CDB', 'CDB'), ('POUPANCA', 'Poupança'), ('PREVIDENCIA', 'Previdência Privada'), ('TESOURO', 'Tesouro Direto'), ('ACOES', 'Ações'), ('FII', 'Fundos Imobiliários')], max_length=20, verbose_name='Tipo')),
                ('instituicao', models.CharField(max_length=100, verbose_name='Instituição Financeira')),
                ('data_inicio', models.DateField(verbose_name='Data da Aplicação')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data do Vencimento')),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Valor Inicial')),
                ('saldo_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Saldo Atual')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
                'db_table': 'investimento',
                'ordering': ['nome_investimento'],
            },
        ),
    ]
