# Generated by Django 6.0.2 on 2026-09-10 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_investimento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investimentocreate',
            old_name='data_inicio',
            new_name='data_aplicacao',
        ),
        migrations.RenameField(
            model_name='investimentocreate',
            old_name='data_fim',
            new_name='data_vencimento',
        ),
    ]
